/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.EntregasDAO;
import DTO.EntregasDTO;

/**
 *
 * @author Gabriel Possato
 */
public class frmEntregasVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmEntregasVIEW
     */
    public frmEntregasVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxEndereço_Entregas = new javax.swing.JTextField();
        PEDIDO = new javax.swing.JLabel();
        jtxIDPedido_Entregas = new javax.swing.JTextField();
        DATA_ENTREGA = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnEnviar_Entregas = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        TÍTULO = new javax.swing.JLabel();
        ENDEREÇO = new javax.swing.JLabel();
        jtxDataEntrega_Entregas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxEndereço_Entregas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxEndereço_Entregas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxEndereço_Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxEndereço_EntregasActionPerformed(evt);
            }
        });

        PEDIDO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        PEDIDO.setText("ID do Pedido:");

        jtxIDPedido_Entregas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxIDPedido_Entregas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxIDPedido_Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIDPedido_EntregasActionPerformed(evt);
            }
        });

        DATA_ENTREGA.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        DATA_ENTREGA.setText("Data da Entrega:");

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEnviar_Entregas.setBackground(new java.awt.Color(0, 153, 153));
        btnEnviar_Entregas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnEnviar_Entregas.setText("ENVIAR");
        btnEnviar_Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar_EntregasActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        TÍTULO.setBackground(new java.awt.Color(153, 0, 51));
        TÍTULO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TÍTULO.setForeground(new java.awt.Color(255, 255, 255));
        TÍTULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TÍTULO.setText("Entregas");
        TÍTULO.setOpaque(true);

        ENDEREÇO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        ENDEREÇO.setText("Endereço:");

        try {
            jtxDataEntrega_Entregas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxDataEntrega_Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxDataEntrega_EntregasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TÍTULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEnviar_Entregas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimpar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVoltar))
                                    .addComponent(ENDEREÇO)
                                    .addComponent(PEDIDO)
                                    .addComponent(DATA_ENTREGA))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxEndereço_Entregas, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                    .addComponent(jtxIDPedido_Entregas, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jtxDataEntrega_Entregas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TÍTULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ENDEREÇO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxEndereço_Entregas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PEDIDO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxIDPedido_Entregas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DATA_ENTREGA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxDataEntrega_Entregas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar_Entregas)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxEndereço_EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxEndereço_EntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxEndereço_EntregasActionPerformed

    private void jtxIDPedido_EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIDPedido_EntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIDPedido_EntregasActionPerformed

    private void jtxDataEntrega_EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxDataEntrega_EntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDataEntrega_EntregasActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
                
        dispose();
        new LoginVIEW().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        jtxDataEntrega_Entregas.setText("");
        jtxEndereço_Entregas.setText("");
        jtxIDPedido_Entregas.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviar_EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar_EntregasActionPerformed
        String DataEntrega_EntregasVIEW, Endereço_EntregasVIEW;
        int IDPedido_EntregasVIEW;
        
        DataEntrega_EntregasVIEW = jtxDataEntrega_Entregas.getText();
        Endereço_EntregasVIEW = jtxEndereço_Entregas.getText();
        IDPedido_EntregasVIEW = Integer.parseInt(jtxIDPedido_Entregas.getText());
        
        EntregasDTO objEntregasDTO = new EntregasDTO();
        objEntregasDTO.setDataEntrega_EntregasDTO(DataEntrega_EntregasVIEW);
        objEntregasDTO.setEndereço_EntregasDTO(Endereço_EntregasVIEW);
        objEntregasDTO.setIDPedido_EntregasDTO(IDPedido_EntregasVIEW); 
        
        EntregasDAO objEntregasDAO = new EntregasDAO();
        objEntregasDAO.cadastrarEntregas(objEntregasDTO);
    }//GEN-LAST:event_btnEnviar_EntregasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEntregasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEntregasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEntregasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEntregasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEntregasVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DATA_ENTREGA;
    private javax.swing.JLabel ENDEREÇO;
    private javax.swing.JLabel PEDIDO;
    private javax.swing.JLabel TÍTULO;
    private javax.swing.JButton btnEnviar_Entregas;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField jtxDataEntrega_Entregas;
    private javax.swing.JTextField jtxEndereço_Entregas;
    private javax.swing.JTextField jtxIDPedido_Entregas;
    // End of variables declaration//GEN-END:variables
}
