package VIEW;

import DAO.EstoqueDAO;
import DTO.EstoqueDTO;

/**
 *
 * @author Gabriel Possato
 */
public class frmEstoqueVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmEstoqueVIEW
     */
    public frmEstoqueVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TÍTULO = new javax.swing.JLabel();
        FORNECEDOR = new javax.swing.JLabel();
        jtxIDFornecedor_Estoque = new javax.swing.JTextField();
        QUANTIDADE = new javax.swing.JLabel();
        jtxQntd_Estoque = new javax.swing.JTextField();
        FILIAL = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnEnviar_Estoque = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jtxIDFilial_Estoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TÍTULO.setBackground(new java.awt.Color(153, 0, 51));
        TÍTULO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TÍTULO.setForeground(new java.awt.Color(255, 255, 255));
        TÍTULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TÍTULO.setText("Estoque");
        TÍTULO.setOpaque(true);

        FORNECEDOR.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        FORNECEDOR.setText("ID do Fornecedor:");

        jtxIDFornecedor_Estoque.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxIDFornecedor_Estoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxIDFornecedor_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIDFornecedor_EstoqueActionPerformed(evt);
            }
        });

        QUANTIDADE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        QUANTIDADE.setText("Quantidade:");

        jtxQntd_Estoque.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxQntd_Estoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxQntd_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxQntd_EstoqueActionPerformed(evt);
            }
        });

        FILIAL.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        FILIAL.setText("ID da Filial:");

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEnviar_Estoque.setBackground(new java.awt.Color(0, 153, 153));
        btnEnviar_Estoque.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnEnviar_Estoque.setText("ENVIAR");
        btnEnviar_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar_EstoqueActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jtxIDFilial_Estoque.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxIDFilial_Estoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxIDFilial_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIDFilial_EstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TÍTULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar_Estoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVoltar))
                            .addComponent(FORNECEDOR)
                            .addComponent(QUANTIDADE)
                            .addComponent(FILIAL))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxIDFornecedor_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(jtxIDFilial_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(jtxQntd_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TÍTULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FORNECEDOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxIDFornecedor_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QUANTIDADE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxQntd_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FILIAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxIDFilial_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar_Estoque)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxIDFornecedor_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIDFornecedor_EstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIDFornecedor_EstoqueActionPerformed

    private void jtxQntd_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxQntd_EstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxQntd_EstoqueActionPerformed

    private void jtxIDFilial_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIDFilial_EstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIDFilial_EstoqueActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
                
        dispose();
        new LoginVIEW().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        jtxIDFilial_Estoque.setText("");
        jtxIDFornecedor_Estoque.setText("");
        jtxQntd_Estoque.setText("");    
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviar_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar_EstoqueActionPerformed
        int IDFilial_EstoqueVIEW, IDFornecedor_EstoqueVIEW, Qntd_EstoqueVIEW;
        
        IDFilial_EstoqueVIEW = Integer.parseInt(jtxIDFilial_Estoque.getText());
        IDFornecedor_EstoqueVIEW = Integer.parseInt(jtxIDFornecedor_Estoque.getText());
        Qntd_EstoqueVIEW = Integer.parseInt(jtxQntd_Estoque.getText());
        
        EstoqueDTO objEstoqueDTO = new EstoqueDTO();
        objEstoqueDTO.setIDFilial_EstoqueDTO(IDFilial_EstoqueVIEW);
        objEstoqueDTO.setIDFornecedor_EstoqueDTO(IDFornecedor_EstoqueVIEW);
        objEstoqueDTO.setQntd_EstoqueDTO(Qntd_EstoqueVIEW);
                
        EstoqueDAO objEstoqueDAO = new EstoqueDAO();
        objEstoqueDAO.cadastrarEstoque(objEstoqueDTO);  
    }//GEN-LAST:event_btnEnviar_EstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstoqueVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstoqueVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstoqueVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstoqueVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstoqueVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FILIAL;
    private javax.swing.JLabel FORNECEDOR;
    private javax.swing.JLabel QUANTIDADE;
    private javax.swing.JLabel TÍTULO;
    private javax.swing.JButton btnEnviar_Estoque;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField jtxIDFilial_Estoque;
    private javax.swing.JTextField jtxIDFornecedor_Estoque;
    private javax.swing.JTextField jtxQntd_Estoque;
    // End of variables declaration//GEN-END:variables
}
