package VIEW;

import DAO.FilialDAO;
import DTO.FilialDTO;

/**
 *
 * @author Gabriel Possato
 */
public class frmFilialVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmFilialVIEW
     */
    public frmFilialVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TÍTULO = new javax.swing.JLabel();
        MESAS = new javax.swing.JLabel();
        ENDEREÇO = new javax.swing.JLabel();
        jtxEndereço_Filiais = new javax.swing.JTextField();
        EMAIL = new javax.swing.JLabel();
        jtxEmail_Filiais = new javax.swing.JTextField();
        TELEFONE = new javax.swing.JLabel();
        AVALIAÇÃO = new javax.swing.JLabel();
        jtxQntdMesas_Filiais = new javax.swing.JTextField();
        jtxTelefone_Filiais = new javax.swing.JFormattedTextField();
        jtxAvaliação_Filiais = new javax.swing.JFormattedTextField();
        btnVoltar = new javax.swing.JButton();
        btnEnviar_Filiais = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TÍTULO.setBackground(new java.awt.Color(153, 0, 51));
        TÍTULO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TÍTULO.setForeground(new java.awt.Color(255, 255, 255));
        TÍTULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TÍTULO.setText("Filiais");
        TÍTULO.setOpaque(true);

        MESAS.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        MESAS.setText("Quantidade de mesas:");

        ENDEREÇO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        ENDEREÇO.setText("Endereço:");

        jtxEndereço_Filiais.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxEndereço_Filiais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxEndereço_Filiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxEndereço_FiliaisActionPerformed(evt);
            }
        });

        EMAIL.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        EMAIL.setText("Email:");

        jtxEmail_Filiais.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxEmail_Filiais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxEmail_Filiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxEmail_FiliaisActionPerformed(evt);
            }
        });

        TELEFONE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TELEFONE.setText("Telefone:");

        AVALIAÇÃO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        AVALIAÇÃO.setText("Avaliação:");

        jtxQntdMesas_Filiais.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxQntdMesas_Filiais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxQntdMesas_Filiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxQntdMesas_FiliaisActionPerformed(evt);
            }
        });

        jtxTelefone_Filiais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jtxTelefone_Filiais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jtxAvaliação_Filiais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jtxAvaliação_Filiais.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEnviar_Filiais.setBackground(new java.awt.Color(0, 153, 153));
        btnEnviar_Filiais.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnEnviar_Filiais.setText("ENVIAR");
        btnEnviar_Filiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar_FiliaisActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TÍTULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar_Filiais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVoltar))
                            .addComponent(ENDEREÇO)
                            .addComponent(EMAIL)
                            .addComponent(TELEFONE)
                            .addComponent(MESAS)
                            .addComponent(AVALIAÇÃO))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxQntdMesas_Filiais, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(jtxEndereço_Filiais, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(jtxEmail_Filiais, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addComponent(jtxTelefone_Filiais)
                            .addComponent(jtxAvaliação_Filiais))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TÍTULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ENDEREÇO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxEndereço_Filiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(EMAIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxEmail_Filiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TELEFONE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxTelefone_Filiais, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MESAS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxQntdMesas_Filiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AVALIAÇÃO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxAvaliação_Filiais, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar_Filiais)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxEndereço_FiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxEndereço_FiliaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxEndereço_FiliaisActionPerformed

    private void jtxEmail_FiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxEmail_FiliaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxEmail_FiliaisActionPerformed

    private void jtxQntdMesas_FiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxQntdMesas_FiliaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxQntdMesas_FiliaisActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
                
        dispose();
        new LoginVIEW().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        jtxAvaliação_Filiais.setText("");
        jtxEmail_Filiais.setText("");
        jtxEndereço_Filiais.setText("");
        jtxQntdMesas_Filiais.setText("");
        jtxTelefone_Filiais.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviar_FiliaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar_FiliaisActionPerformed
        String Avaliação_FiliaisVIEW, Email_FiliaisVIEW, Endereço_FiliaisVIEW, Telefone_FiliaisVIEW;
        int QntdMesas_FiliaisVIEW;

        Avaliação_FiliaisVIEW = jtxAvaliação_Filiais.getText();
        Email_FiliaisVIEW = jtxEmail_Filiais.getText();
        Endereço_FiliaisVIEW = jtxEndereço_Filiais.getText();
        Telefone_FiliaisVIEW = jtxTelefone_Filiais.getText();
        QntdMesas_FiliaisVIEW = Integer.parseInt(jtxQntdMesas_Filiais.getText());

        FilialDTO objFilialDTO = new FilialDTO();
        objFilialDTO.setAvaliação_FiliaisDTO(Avaliação_FiliaisVIEW);
        objFilialDTO.setEmail_FiliaisDTO(Email_FiliaisVIEW);
        objFilialDTO.setEndereço_FiliaisDTO(Endereço_FiliaisVIEW);
        objFilialDTO.setQtndMesas_FiliaisDTO(QntdMesas_FiliaisVIEW);
        objFilialDTO.setTelefone_FiliaisDTO(Telefone_FiliaisVIEW);
                                
        FilialDAO objFilialDAO = new FilialDAO();
        objFilialDAO.cadastrarFilial(objFilialDTO);
    }//GEN-LAST:event_btnEnviar_FiliaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFilialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFilialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFilialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFilialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFilialVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AVALIAÇÃO;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel ENDEREÇO;
    private javax.swing.JLabel MESAS;
    private javax.swing.JLabel TELEFONE;
    private javax.swing.JLabel TÍTULO;
    private javax.swing.JButton btnEnviar_Filiais;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField jtxAvaliação_Filiais;
    private javax.swing.JTextField jtxEmail_Filiais;
    private javax.swing.JTextField jtxEndereço_Filiais;
    private javax.swing.JTextField jtxQntdMesas_Filiais;
    private javax.swing.JFormattedTextField jtxTelefone_Filiais;
    // End of variables declaration//GEN-END:variables
}
