/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.FornecedoresDAO;
import DTO.FornecedoresDTO;

/**
 *
 * @author gabri
 */
public class frmFornecedoresVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedoresVIEW
     */
    public frmFornecedoresVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxTelefone_Fornecedores = new javax.swing.JFormattedTextField();
        jtxCNPJ_Fornecedores = new javax.swing.JFormattedTextField();
        TÍTULO = new javax.swing.JLabel();
        NOME = new javax.swing.JLabel();
        jtxNome_Fornecedores = new javax.swing.JTextField();
        MATERIAL = new javax.swing.JLabel();
        VALOR = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnEnviar_Fornecedores = new javax.swing.JButton();
        EMAIL = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jtxEmail_Fornecedores = new javax.swing.JTextField();
        TELEFONE = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        jtxMaterial_Fornecedores = new javax.swing.JTextField();
        jtxValor_Fornecedores = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxTelefone_Fornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jtxTelefone_Fornecedores.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jtxCNPJ_Fornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jtxCNPJ_Fornecedores.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TÍTULO.setBackground(new java.awt.Color(153, 0, 51));
        TÍTULO.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TÍTULO.setForeground(new java.awt.Color(255, 255, 255));
        TÍTULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TÍTULO.setText("Fornecedores");
        TÍTULO.setOpaque(true);

        NOME.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        NOME.setText("Nome:");

        jtxNome_Fornecedores.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxNome_Fornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxNome_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNome_FornecedoresActionPerformed(evt);
            }
        });

        MATERIAL.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        MATERIAL.setText("Tipo de Material:");

        VALOR.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        VALOR.setText("Valor do Material:");

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEnviar_Fornecedores.setBackground(new java.awt.Color(0, 153, 153));
        btnEnviar_Fornecedores.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnEnviar_Fornecedores.setText("ENVIAR");
        btnEnviar_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar_FornecedoresActionPerformed(evt);
            }
        });

        EMAIL.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        EMAIL.setText("Email:");

        btnLimpar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jtxEmail_Fornecedores.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxEmail_Fornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxEmail_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxEmail_FornecedoresActionPerformed(evt);
            }
        });

        TELEFONE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        TELEFONE.setText("Telefone:");

        CNPJ.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        CNPJ.setText("CNPJ:");

        jtxMaterial_Fornecedores.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxMaterial_Fornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxMaterial_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxMaterial_FornecedoresActionPerformed(evt);
            }
        });

        jtxValor_Fornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jtxValor_Fornecedores.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ###,###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TÍTULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxNome_Fornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(jtxCNPJ_Fornecedores)
                            .addComponent(jtxMaterial_Fornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(jtxEmail_Fornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(jtxTelefone_Fornecedores)))
                    .addComponent(jtxValor_Fornecedores)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar_Fornecedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVoltar))
                            .addComponent(NOME)
                            .addComponent(CNPJ)
                            .addComponent(MATERIAL)
                            .addComponent(EMAIL)
                            .addComponent(TELEFONE)
                            .addComponent(VALOR))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TÍTULO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxNome_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxCNPJ_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MATERIAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxMaterial_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EMAIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxEmail_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TELEFONE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxTelefone_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VALOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxValor_Fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar_Fornecedores)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxNome_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNome_FornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNome_FornecedoresActionPerformed

    private void jtxEmail_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxEmail_FornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxEmail_FornecedoresActionPerformed

    private void jtxMaterial_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxMaterial_FornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxMaterial_FornecedoresActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
                
        dispose();
        new LoginVIEW().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        jtxCNPJ_Fornecedores.setText("");
        jtxEmail_Fornecedores.setText("");
        jtxMaterial_Fornecedores.setText("");
        jtxNome_Fornecedores.setText("");
        jtxTelefone_Fornecedores.setText("");
        jtxValor_Fornecedores.setText("");     
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEnviar_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar_FornecedoresActionPerformed
        String CNPJ_FornecedoresVIEW, Email_FornecedoresVIEW, Material_FornecedoresVIEW, Nome_FornecedoresVIEW, Telefone_FornecedoresVIEW, Valor_FornecedoresVIEW; 
        
        CNPJ_FornecedoresVIEW = jtxCNPJ_Fornecedores.getText();
        Email_FornecedoresVIEW = jtxEmail_Fornecedores.getText();
        Material_FornecedoresVIEW = jtxMaterial_Fornecedores.getText();
        Nome_FornecedoresVIEW = jtxNome_Fornecedores.getText();
        Telefone_FornecedoresVIEW = jtxTelefone_Fornecedores.getText();
        Valor_FornecedoresVIEW = jtxValor_Fornecedores.getText();
        
        FornecedoresDTO objFornecedorDTO = new FornecedoresDTO();
        objFornecedorDTO.setCNPJ_FornecedoresDTO(CNPJ_FornecedoresVIEW);
        objFornecedorDTO.setEmail_FornecedoresDTO(Email_FornecedoresVIEW);
        objFornecedorDTO.setMaterial_FornecedoresDTO(Material_FornecedoresVIEW);
        objFornecedorDTO.setNome_FornecedoresDTO(Nome_FornecedoresVIEW);
        objFornecedorDTO.setTelefone_FornecedoresDTO(Telefone_FornecedoresVIEW);
        objFornecedorDTO.setValor_FornecedoresDTO(Valor_FornecedoresVIEW);
        
        FornecedoresDAO objFornecedoresDAO = new FornecedoresDAO();
        objFornecedoresDAO.cadastrarFornecedor(objFornecedorDTO);
    }//GEN-LAST:event_btnEnviar_FornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFornecedoresVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFornecedoresVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFornecedoresVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFornecedoresVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFornecedoresVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CNPJ;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel MATERIAL;
    private javax.swing.JLabel NOME;
    private javax.swing.JLabel TELEFONE;
    private javax.swing.JLabel TÍTULO;
    private javax.swing.JLabel VALOR;
    private javax.swing.JButton btnEnviar_Fornecedores;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField jtxCNPJ_Fornecedores;
    private javax.swing.JTextField jtxEmail_Fornecedores;
    private javax.swing.JTextField jtxMaterial_Fornecedores;
    private javax.swing.JTextField jtxNome_Fornecedores;
    private javax.swing.JFormattedTextField jtxTelefone_Fornecedores;
    private javax.swing.JFormattedTextField jtxValor_Fornecedores;
    // End of variables declaration//GEN-END:variables
}
