package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Possato
 */
public class LoginVIEW extends javax.swing.JFrame {

    /**
     * Creates new form LoginVIEW
     */
    public LoginVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        txtNome_Usuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        txtSenha_Usuario = new javax.swing.JTextField();
        buttonEntrar_Usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setText("NOME DO USUÁRIO:");

        labelSenha.setText("SENHA DO USUÁRIO:");

        buttonEntrar_Usuario.setText("ENTRAR");
        buttonEntrar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrar_UsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNome_Usuario)
                        .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSenha_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addComponent(buttonEntrar_Usuario))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEntrar_Usuario)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEntrar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrar_UsuarioActionPerformed
         try {
            String Nome_Texto;
            String Senha_Texto;
         
            Nome_Texto = txtNome_Usuario.getText();
            Senha_Texto = txtSenha_Usuario.getText();
         
            UsuarioDTO classUsuarioDTO = new UsuarioDTO();
            classUsuarioDTO.setNome(Nome_Texto);
            classUsuarioDTO.setSenha(Senha_Texto);
            
            UsuarioDAO objUsuarioDAO = new UsuarioDAO();
            
            ResultSet rsUsuarioDAO = objUsuarioDAO.autenticacaoUsuario(classUsuarioDTO);
            
                if (rsUsuarioDAO.next()) {
                    // USUÁRIO E SENHA ESTÃO NO BANCO - TELA APARECE
                    
                    EnvioVIEW objEnvioVIEW = new EnvioVIEW();
                    objEnvioVIEW.setVisible(true);
                    
                    dispose();
                }
                
                else {
                   // ENVIAR MENSAGEM DIZENDO QUE ESTÁ USUÁRIO OU SENHA ESTÃO INCORRETOS - TELA NÃO APARECE
                   
                   JOptionPane.showMessageDialog(null, "USUÁRIO OU SENHA INVÁLIDOS. TENTE NOVAMENTE!");
                }
         }
         
         catch (SQLException erro) {
             JOptionPane.showMessageDialog(null, "ERRO NO LOGINVIEW.JAVA: " + erro);
         }
    }//GEN-LAST:event_buttonEntrar_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEntrar_Usuario;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JTextField txtNome_Usuario;
    private javax.swing.JTextField txtSenha_Usuario;
    // End of variables declaration//GEN-END:variables
}
